services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nihatnihat
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge
